import java_cup.runtime.*;
public class ManejoDeErrores{

    public String Errores(int tipo){
        String men=" ";
        switch (tipo){

          case 0:men = "E=0 No hay nada que analizar";break;
          case 1:men = "E=1 Algo salió mal verifica el inicio del programa";break;
          case 2:men = "E=2 Verifica el método SETUP";break;
          case 3:men = "E=3 Falta una llave que abre { en la frecuencia del oscilador";break;
          case 4:men = "E=4 Verifica el método SETUP, que este presente en el programa";break;
          case 5:men = "E=5 Error verifica el metodo SETUP";break;
          case 6:men = "E=6 Verifica el RETARDO y el método CICLO.";break;
          case 7:men = "E=7 Error En el metodo MAIN falta una llave";break;
          case 8:men = "E=8 Error verifica el ID";break;
          case 9:men = "E=9 Error verifica que el metodo SETUP contenga la palabra reservada VOID";break;
          case 10:men = "E=10 Error No definiste la variable con VAR o CONSTANTE";break;
          case 11:men = "E=11 Error Verifica la declaracion de variables";break;
          case 12:men = "E=12 Error verifica que tu metodo contenga VOID";break;
          case 13:men = "E=13 Error en el identificafor de tu metodo";break;
          case 14:men = "E=14 Error verifica que tu metodo INTERRUPT sea valido";break;
          case 15:men = "E=15 Error verifica el ID del metodo INTERRUPT";break;
          case 16:men = "E=16 Error verifica que tu metodo INTERRUPT contenga una parentesis que abre";break;
          case 17:men = "E=17 Error verifica que tu metodo INTERRUPT contenga una parentesis que cierra";break;
          case 18:men = "E=18 Error en el valor a la asignación de puertos";break;
          case 19:men = "E=19 Error en o cerca de la asignación a TE";break;
          case 20:men = "E=20 Error en o cerca de la asignación a TD";break;
          case 21:men = "E=21 Error en o cerca de la asignación a TC";break;
          case 22:men = "E=22 Error en o cerca de la asignación a PE3";break;
          case 23:men = "E=23 Error en o cerca de la asignación a TB";break;
          case 24:men = "E=24 Error en o cerca de la asignación a TA";break;
          case 25:men = "E=25 Error en o cerca de la asignación a PE2";break;
          case 26:men = "E=26 Error en o cerca de la asignación a PE1";break;
          case 27:men = "E=27 Error en o cerca de la asignación a PE0";break;
          case 28:men = "E=28 Error en o cerca de la asignación a TD7";break;
          case 29:men = "E=29 Error en o cerca de la asignación a TD6";break;
          case 30:men = "E=30 Error en o cerca de la asignación a OPTIONREG_PS2";break;
          case 31:men = "E=31 Error en o cerca de la asignación a OPTIONREG_PS1";break;
          case 32:men = "E=32 Error en o cerca de la asignación a TD5";break;
          case 33:men = "E=33 Error en o cerca de la asignación a TD4";break;
          case 34:men = "E=34 Error en o cerca de la asignación a OPTIONREG_PS0";break;
          case 35:men = "E=35 Error en o cerca de la asignación a TD3";break;
          case 36:men = "E=36 Error en la declaracion de los puertos";break;
          case 37:men = "E=37 Error en o cerca de la asignación a TD2";break;
          case 38:men = "E=38 Error en o cerca de la asignación a TD1";break;
          case 39:men = "E=39 Error en o cerca de la asignación a TD0";break;
          case 40:men = "E=40 Error falta parentesis en la comparacion cerca del SI";break;
          case 41:men = "E=41 Error en o cerca de la asignación a OPTIONREG_RBPU";break;
          case 42:men = "E=42 Error en o cerca de la asignación a PD7";break;
          case 43:men = "E=43 Error en o cerca de la asignación a PD6";break;
          case 44:men = "E=44 Error en o cerca de la asignación a PD5";break;
          case 45:men = "E=45 Error en o cerca de la asignación a PD4";break;
          case 46:men = "E=46 Error en o cerca de la asignación a PD3";break;
          case 47:men = "E=47 Error en o cerca de la asignación a PD2";break;
          case 48:men = "E=48 Error en o cerca de la asignación a ADCON0_GO";break;
          case 49:men = "E=49 Error en o cerca de la asignación a PD1";break;
          case 50:men = "E=50 Error en o cerca de la asignación a TC7";break;
          case 51:men = "E=51 Error en o cerca de la asignación a PD0";break;
          case 52:men = "E=52 Error en o cerca de la asignación a TC6";break;
          case 53:men = "E=53 Error en o cerca de la asignación a TC5";break;
          case 54:men = "E=54 Error en o cerca de la asignación a TC4";break;
          case 55:men = "E=55 Error en o cerca de la asignación a TC3";break;
          case 56:men = "E=56 Error en o cerca de la asignación a TMR0";break;
          case 57:men = "E=57 Error en o cerca de la asignación a TC2";break;
          case 58:men = "E=58 Error en o cerca de la asignación a TC1";break;
          case 59:men = "E=59 Error en o cerca de la asignación a TC0";break;
          case 60:men = "E=60 Error en o cerca de la asignación a ADCON0_ADCS1";break;
          case 61:men = "E=61 Error en o cerca de la asignación a ADCON0_ADCS0";break;
          case 62:men = "E=62 Error en o cerca de la asignación a OPTIONREG_PS";break;
          case 63:men = "E=63 Error en o cerca de la asignación a ADCON0_CHS3";break;
          case 64:men = "E=64 Error en o cerca de la asignación a ADCON0_CHS2";break;
          case 65:men = "E=65 Error en o cerca de la asignación a ADCON0_CHS1";break;
          case 66:men = "E=66 Error en o cerca de la asignación a ADCON0_CHS0";break;
          case 67:men = "E=67 Error en o cerca de la asignación a PC7";break;
          case 68:men = "E=68 Error en o cerca de la asignación a PC6";break;
          case 69:men = "E=69 Error en o cerca de la asignación a PC5";break;
          case 70:men = "E=70 Error en o cerca de la asignación a PC4";break;
          case 71:men = "E=71 Error en o cerca de la asignación a PC3";break;
          case 72:men = "E=72 Error en o cerca de la asignación a PC2";break;
          case 73:men = "E=73 Error en o cerca de la asignación a PC1";break;
          case 74:men = "E=74 Error en o cerca de la asignación a TB7";break;
          case 75:men = "E=75 Error en o cerca de la asignación a PC0";break;
          case 76:men = "E=76 Error en o cerca de la asignación a TB6";break;
          case 77:men = "E=77 Error en o cerca de la asignación a OPTIONREG_T0SE";break;
          case 78:men = "E=78 Error en o cerca de la asignación a TB5";break;
          case 79:men = "E=79 Error en o cerca de la asignación a TB4";break;
          case 80:men = "E=80 Error en o cerca de la asignación a TB3";break;
          case 81:men = "E=81 Error en o cerca de la asignación a TB2";break;
          case 82:men = "E=82 Error en o cerca de la asignación a TB1";break;
          case 83:men = "E=83 Error en o cerca de la asignación a TB0";break;
          case 84:men = "E=84 Error en o cerca de la asignación a ANSELH5";break;
          case 85:men = "E=85 Error en o cerca de la asignación a ANSELH4";break;
          case 86:men = "E=86 Error en o cerca de la asignación a ANSELH3";break;
          case 87:men = "E=87 Error en o cerca de la asignación a ANSELH2";break;
          case 88:men = "E=88 Error en o cerca de la asignación a ANSELH1";break;
          case 89:men = "E=89 Error en o cerca de la asignación a ANSELH0";break;
          case 90:men = "E=90 Error en o cerca de la asignación a PB7";break;
          case 91:men = "E=91 Error en o cerca de la asignación a ADCON1_ADFM";break;
          case 92:men = "E=92 Error en o cerca de la asignación a PB6";break;
          case 93:men = "E=93 Error en o cerca de la asignación a PB5";break;
          case 94:men = "E=94 Error en el ciclo WHILE verifica que tenga parentesis";break;
          case 95:men = "E=95 Error en o cerca de la asignación a PB4";break;
          case 96:men = "E=96 Error en o cerca de la asignación a PB3";break;
          case 97:men = "E=97 Error en o cerca de la asignación a PB2";break;
          case 98:men = "E=98 Error en o cerca de la asignación a INTCON";break;
          case 99:men = "E=99 Error en el ciclo RETARDO falta parentesis";break;
          case 100:men = "E=100 Error en o cerca de la asignación a PB1";break;
          case 101:men = "E=101 Error en o cerca de la asignación a PB0";break;
          case 102:men = "E=102 Error en o cerca de la asignación a INTCONINTF";break;
          case 103:men = "E=103 Error en o cerca de la asignación a TA7";break;
          case 104:men = "E=104 Error en o cerca de la asignación a INTCONINTE";break;
          case 105:men = "E=105 Error en o cerca de la asignación a TA6";break;
          case 106:men = "E=106 Error en o cerca de la asignación a TA5";break;
          case 107:men = "E=107 Error en o cerca de la asignación a INTCONT0IF";break;
          case 108:men = "E=108 Error en o cerca de la asignación a TA4";break;
          case 109:men = "E=109 Error en o cerca de la asignación a TA3";break;
          case 110:men = "E=110 Error en o cerca de la asignación a INTCONT0IE";break;
          case 111:men = "E=111 Error en un SWITCH verifica que tenga parentesis";break;
          case 112:men = "E=112 Error en o cerca de la asignación a TA2";break;
          case 113:men = "E=113 Error en o cerca de la asignación a TA1";break;
          case 114:men = "E=114 Error en o cerca de la asignación a TA0";break;
          case 115:men = "E=115 Error en o cerca de RETURN";break;
          case 116:men = "E=116 Error en la asignación de valores a los puertos";break;
          case 117:men = "E=117 Error en o cerca de DELAY";break;
          case 118:men = "E=118 Error en o cerca de la asignación a ANSEL";break;
          case 119:men = "E=119 Error en o cerca de la asignación a PA7";break;
          case 120:men = "E=120 Error en o cerca de la asignación a PA6";break;
          case 121:men = "E=121 Error en o cerca de la asignación a PE";break;
          case 122:men = "E=122 Error en o cerca de la asignación a PD";break;
          case 123:men = "E=123 Error en o cerca de la asignación a PA5";break;
          case 124:men = "E=124 Error en o cerca de la asignación a PC";break;
          case 125:men = "E=125 Error en o cerca de la asignación a PA4";break;
          case 126:men = "E=126 Error en o cerca de la asignación a PA3";break;
          case 127:men = "E=127 Error en o cerca de la asignación a PB";break;
          case 128:men = "E=128 Error en o cerca de la asignación a PA";break;
          case 129:men = "E=129 Error en o cerca de la asignación a PA2";break;
          case 130:men = "E=130 Error en o cerca de la asignación a PA1";break;
          case 131:men = "E=131 Error en o cerca de la asignación a PA0";break;
          case 132:men = "E=132 Error en o cerca de la asignación a INTCONPEIE";break;
          case 133:men = "E=133 Error en el un ID verifica que no este repetido.";break;
          case 134:men = "E=134 Error en o cerca de la asignación a ANSELH";break;
          case 135:men = "E=135 Error en o cerca de la asignación a INTCONGIE";break;
          case 136:men = "E=136 Error en o cerca de la asignación a ADCON0_ADON";break;
          case 137:men = "E=137 Error en o cerca de la asignación a ADCON1_VCFG1";break;
          case 138:men = "E=138 Error en o cerca de la asignación a ADCON1_VCFG0";break;
          case 139:men = "E=139 Error en o cerca de la asignación a OPTIONREG_T0CS";break;
          case 140:men = "E=140 Error en o cerca de la asignación a ANSEL7";break;
          case 141:men = "E=141 Error en o cerca de la asignación a ANSEL6";break;
          case 142:men = "E=142 Error en o cerca de la asignación a TE3";break;
          case 143:men = "E=143 Error en o cerca de la asignación a ANSEL5";break;
          case 144:men = "E=144 Error en o cerca de la asignación a TE2";break;
          case 145:men = "E=145 Error en o cerca de la asignación a ANSEL4";break;
          case 146:men = "E=146 Error en o cerca de la asignación a TE1";break;
          case 147:men = "E=147 Error en o cerca de la asignación a TE0";break;
          case 148:men = "E=148 Error en o cerca de la asignación a ANSEL3";break;
          case 149:men = "E=149 Error en o cerca de la asignación a ANSEL2";break;
          case 150:men = "E=150 Error en o cerca de la asignación a ANSEL1";break;
          case 151:men = "E=151 Error en o cerca de la asignación a INTCONRBIF";break;
          case 152:men = "E=152 Error en o cerca de la asignación a ANSEL0";break;
          case 153:men = "E=153 Error en o cerca de la asignación a INTCONRBIE";break;
          case 154:men = "E=154 Error en o cerca de la asignación a OPTIONREG_INTEDG";break;
          case 155:men = "E=155 Error en o cerca de la asignación a OPTIONREG_PSA";break;
          case 156:men = "E=156 Error en las instrucciones del metodo INTERRUPT";break;
          case 158:men = "E=158 Error falta una llave en el metodo INTERRUPT";break;
          case 159:men = "E=159 Error de asignación en los puertos";break;
          case 160:men = "E=160 Error en la asignación de un puerto";break;
          case 161:men = "E=161 Error en o cerca de la asignación a PD3";break;
          case 162:men = "E=162 Error en o cerca de la asignación a PA1";break;
          case 163:men = "E=163 Error en o cerca de la asignación a INTCONRBIF";break;
          case 164:men = "E=164 Error en o cerca de la asignación a PA0";break;
          case 165:men = "E=165 Error en o cerca de la asignación a PD2";break;
          case 166:men = "E=166 Error en o cerca de la asignación a INTCONRBIE";break;
          case 167:men = "E=167 Error en o cerca de la asignación a PD1";break;
          case 168:men = "E=168 Error en o cerca de la asignación a PD0";break;
          case 169:men = "E=169 Error en o cerca de la asignación a PE";break;
          case 170:men = "E=170 Error en o cerca de la asignación a PD";break;
          case 171:men = "E=171 Error en o cerca de la asignación a PC";break;
          case 172:men = "E=172 Error en o cerca de la asignación a PB";break;
          case 173:men = "E=173 Error en o cerca de la asignación a PA";break;
          case 174:men = "E=174 Error en o cerca de la asignación a PC7";break;
          case 175:men = "E=175 Error en o cerca de la asignación a PC6";break;
          case 176:men = "E=176 Error en o cerca de la asignación a PC5";break;
          case 177:men = "E=177 Error en o cerca de la asignación a PC4";break;
          case 178:men = "E=178 Error en o cerca de la asignación a PC3";break;
          case 179:men = "E=179 Error en o cerca de la asignación a INTCONINTF";break;
          case 180:men = "E=180 Error en o cerca de la asignación a PC2";break;
          case 181:men = "E=181 Error en o cerca de la asignación a INTCONINTE";break;
          case 182:men = "E=182 Error en o cerca de la asignación a PC1";break;
          case 183:men = "E=183 Error en o cerca de la asignación a PC0";break;
          case 184:men = "E=184 Error en o cerca de la asignación a INTCONGIE";break;
          case 185:men = "E=185 Error en o cerca de la asignación a PB7";break;
          case 186:men = "E=186 Error en o cerca de la asignación a PB6";break;
          case 187:men = "E=187 Error en o cerca de la asignación a PB5";break;
          case 188:men = "E=188 Error en o cerca de la asignación a PB4";break;
          case 189:men = "E=189 Error en o cerca de la asignación a PB3";break;
          case 190:men = "E=190 Error en o cerca de la asignación a PB2";break;
          case 191:men = "E=191 Error en o cerca de la asignación a PB1";break;
          case 192:men = "E=192 Error en o cerca de la asignación a PE3";break;
          case 193:men = "E=193 Error en o cerca de la asignación a PB0";break;
          case 194:men = "E=194 Error en o cerca de la asignación a PE2";break;
          case 195:men = "E=195 Error en o cerca de la asignación a PE1";break;
          case 196:men = "E=196 Error en o cerca de la asignación a PE0";break;
          case 197:men = "E=197 Error en o cerca de la asignación a INTCONPEIE";break;
          case 198:men = "E=198 Error en o cerca de la asignación a INTCONT0IF";break;
          case 199:men = "E=199 Error en o cerca de la asignación a INTCONT0IE";break;
          case 200:men = "E=200 Error en o cerca de la asignación a PA7";break;
          case 201:men = "E=201 Error en o cerca de la asignación a PA6";break;
          case 202:men = "E=202 Error en o cerca de la asignación a PA5";break;
          case 203:men = "E=203 Error en o cerca de la asignación a PD7";break;
          case 204:men = "E=204 Error en o cerca de la asignación a PA4";break;
          case 205:men = "E=205 Error en o cerca de la asignación a PD6";break;
          case 206:men = "E=206 Error en o cerca de la asignación a PA3";break;
          case 207:men = "E=207 Error en o cerca de la asignación a PD5";break;
          case 208:men = "E=208 Error en o cerca de la asignación a PD4";break;
          case 209:men = "E=209 Error se espera un punto y coma despues de la asignación de los puertos";break;
          case 210:men = "E=210 Error en o cerca de la asignación a PA2";break;
          case 211:men = "E=211 Error en la asignación de un puerto al valor de otro";break;
          case 212:men = "E=212 Error se espera un punto y coma despues de la asignación de un valor al puerto";break;
          case 213:men = "E=213 Error se espera un punto y coma despues de la asignación de una variable al puerto";break;
          case 214:men = "E=214 Error se espera un punto y coma despues de la asignación de un numero binario al puerto";break;
          case 215:men = "E=215 Error se espera un signo de + para sumar al puerto.";break;
          case 216:men = "E=216 Error se espera un signo de + para sumar al puerto.";break;
          case 217:men = "E=217 Error se espera un punto y coma en la asignación al puerto";break;
          case 218:men = "E=218 Error se espera un punto y coma despues del ID asignado al puerto.";break;
          case 219:men = "E=219 Error en la asignación al puerto";break;
          case 220:men = "E=220 Error en la asignación al puerto";break;
          case 221:men = "E=221 Error en la asignación al puerto";break;
          case 222:men = "E=222 Error en la asignación al puerto";break;
          case 223:men = "E=223 Error en la asignación al puerto";break;
          case 224:men = "E=224 Error se espera un signo de +";break;
          case 225:men = "E=225 Error falta un parentesis";break;
          case 226:men = "E=226 Error en o cerca del recorrimiento de bits hacia la derecha";break;
          case 227:men = "E=227 Error en el decremento a una variable falta un signo de -";break;
          case 228:men = "E=228 Error en o cerca del recorrimiento de bits hacia la izquierda";break;
          case 229:men = "E=229 Error en la exprecion falta un parentesis";break;
          case 230:men = "E=230 Error en o cerca de una variable";break;
          case 231:men = "E=231 Error en o cerca de la expresión que asignaste un numero";break;
          case 232:men = "E=232 Error en o cerca de la variable falta un parentesis (";break;
          case 233:men = "E=233 Error en la exprecion declarada";break;
          case 234:men = "E=234 Error en la operacion de asignacion falta un parentesis )";break;
          case 235:men = "E=235 Error falta un ; en la expresión";break;
          case 236:men = "E=236 Error falta un ; en la expresión";break;
          case 237:men = "E=237 Error verifica que la variable este declara";break;
          case 238:men = "E=238 Error en la asignacion verifica el numero.";break;
          case 239:men = "E=239 Error en el recorrimiento de bits a la izquierda verifica el numero";break;
          case 240:men = "E=240 Error en el recorrimiento a la izquiera verifica el ;";break;
          case 241:men = "E=241 Verifica el decremento falta un signo de -";break;
          case 242:men = "E=242 Error verifica el decremento falta un ;";break;
          case 243:men = "E=243 Error en el recorrimiento de bits a la derecha verifica el numero";break;
          case 244:men = "E=244 Error en el recorrimiento a la derecha verifica el ;";break;
          case 245:men = "E=245 Error en el numero hexadecimal verifica";break;
          case 246:men = "E=246 Error verifica la exprecion declarada";break;
          case 247:men = "E=247 Error numero con punto flotante invalido";break;
          case 248:men = "E=248 Error numero binario no valido";break;
          case 249:men = "E=249 Error numero no valido";break;
          case 250:men = "E=250 Error en la expreción verica que sea correcta";break;
          case 251:men = "E=251 Error en la variable verifica sea correcta";break;
          case 252:men = "E=252 Error en expresion matematica";break;
          case 253:men = "E=253 Error en el caracter";break;
          case 254:men = "E=254 Error en instruccion o operador matematico";break;
          case 255:men = "E=255 Error en expresion logica";break;
          case 256:men = "E=256 Error en operador mas";break;
          case 257:men = "E=257 Error en operador menos";break;
          case 258:men = "E=258 Error en operador division";break;
          case 259:men = "E=259 Error falta punto y coma";break;
          case 260:men = "E=260 Error en parentesis o expresion";break;
          case 261:men = "E=261 Error en expresion";break;
          case 262:men = "E=262 Falta o sobra parentesis";break;
          case 263:men = "E=263 Falta punto y coma";break;
          case 264:men = "E=264 Falta punto y coma";break;
          case 265:men = "E=265 Error en operador matematico";break;
          case 266:men = "E=266 Error en operador matematico";break;
          case 267:men = "E=267 Error en operador matematico";break;
          case 268:men = "E=268 Error en operador matematico";break;
          case 269:men = "E=269 Error en operador matematico";break;
          case 270:men = "E=270 Error en operador matematico";break;
          case 271:men = "E=271 Error en operador matematico";break;
          case 272:men = "E=272 Falta o sobra parentesis derecho";break;
          case 273:men = "E=273 Falta o sobra parentesis";break;
          case 274:men = "E=274 Error en expresion";break;
          case 275:men = "E=275 Error en expresion";break;
          case 276:men = "E=276 Error en parentesis";break;
          case 277:men = "E=277 Error en parentesis derecho";break;
          case 278:men = "E=278 Falta o sobra parentesis";break;
          case 279:men = "E=279 Error en parentesis";break;
          case 280:men = "E=280 Error en expresion";break;
          case 281:men = "E=281 Error en parentesis";break;
          case 282:men = "E=282 Error en expresion";break;
          case 283:men = "E=283 Error en parentesis o expresion matematica";break;
          case 284:men = "E=284 Falta o sobra parentesis derecho";break;
          case 285:men = "E=285 Falta o sobra parentesis derecho";break;
          case 286:men = "E=286 Falta o sobra parentesis derecho";break;
          case 287:men = "E=287 Error en expresion";break;
          case 288:men = "E=288 Error en expresion";break;
          case 289:men = "E=289 Error en parentesis derecho";break;
          case 290:men = "E=290 Error en operador";break;
          case 291:men = "E=291 Error en expresion";break;
          case 292:men = "E=292 Error en expresion";break;
          case 293:men = "E=293 Error en parentesis";break;
          case 294:men = "E=294 Error en parentesis";break;
          case 295:men = "E=295 Eror en recorrimiento de bits";break;
          case 296:men = "E=296 Error en recorrimiento de bits";break;
          case 297:men = "E=297 Error en el numero";break;
          case 298:men = "E=298 Falta o sobra punto y coma";break;
          case 299:men = "E=299 Error en el numero";break;
          case 300:men = "E=300 Falta o sobra punto y coma";break;
          case 301:men = "E=301 Error en operador";break;
          case 302:men = "E=302 Error en expresion";break;
          case 303:men = "E=303 Error en expresion";break;
          case 304:men = "E=304 Error en expresion";break;
          case 305:men = "E=305 Falta punto y coma";break;
          case 306:men = "E=306 Falta punto y coma";break;
          case 307:men = "E=307 Falta punto y coma";break;
          case 308:men = "E=308 Error en operador matematico";break;
          case 309:men = "E=309 Falta punto y coma";break;
          case 310:men = "E=310 Error en llave";break;
          case 311:men = "E=311 Error en numero";break;
          case 312:men = "E=312 Error en llave";break;
          case 313:men = "E=313 Falta punto y coma";break;
          case 314:men = "E=314 Error en la instruccion o expresion";break;
          case 315:men = "E=315 Falta punto y coma";break;
          case 316:men = "E=316 Error en los puertos";break;
          case 317:men = "E=317 Error en la expresion";break;
          case 318:men = "E=318 Error en los puertos";break;
          case 319:men = "E=319 Error en parentesis";break;
          case 320:men = "E=320 Error en sentencia case";break;
          case 321:men = "E=321 Error en sentencia case";break;
          case 322:men = "E=322 Error en sentenca default";break;
          case 323:men = "E=323 Error en la expresion";break;
          case 324:men = "E=324 Error en la expresion";break;
          case 325:men = "E=325 Error en los puesrtos";break;
          case 326:men = "E=326 Error en la instruccion o sentencia";break;
          case 327:men = "E=327 Error en los puertos";break;
          case 328:men = "E=328 Error en la instruccion o sentencia";break;
          case 329:men = "E=329 Error al final de la instruccion";break;
          case 330:men = "E=330 Error en default";break;
          case 331:men = "E=331 Error en expresion";break;
          case 332:men = "E=332 Error en expresion";break;
          case 333:men = "E=333 Error en puertos";break;
          case 334:men = "E=334 Error en instruccion";break;
          case 335:men = "E=335 Error en puertos";break;
          case 336:men = "E=336 Error en instrucciones";break;
          case 337:men = "E=337 Error en switch";break;
          case 338:men = "E=338 Error en parentesis";break;
          case 339:men = "E=339 Error en sentencia case";break;
          case 340:men = "E=340 Error en sentencia case";break;
          case 341:men = "E=341 Error al final de la instruccion";break;
          case 342:men = "E=342 Error en switch";break;
          case 343:men = "E=343 Error en parentesis";break;
          case 344:men = "E=344 Error en numero";break;
          case 345:men = "E=345 Error en parentesis";break;
          case 346:men = "E=346 Falta punto y coma";break;
          case 347:men = "E=347 Error en puertos";break;
          case 348:men = "E=348 Error en numero";break;
          case 349:men = "E=349 Error en condicion";break;
          case 350:men = "E=350 Error en variable";break;
          case 351:men = "E=351 Error en expresion";break;
          case 352:men = "E=352 Error en numero binario";break;
          case 353:men = "E=353 Error en signo o en condicion";break;
          case 354:men = "E=354 Error en numero hexadecimal";break;
          case 355:men = "E=355 Error en puertos";break;
          case 356:men = "E=356 Error en AND";break;
          case 357:men = "E=357 Error en signo menor o igual";break;
          case 358:men = "E=358 Error en signo menor";break;
          case 359:men = "E=359 Error en signo mayor o igual";break;
          case 360:men = "E=360 Error en signo mayor";break;
          case 361:men = "E=361 Error en igualacion";break;
          case 362:men = "E=362 Error en puertos";break;
          case 363:men = "E=363 Error en signo diferente de";break;
          case 364:men = "E=364 Error en signo OR";break;
          case 365:men = "E=365 Error en numero";break;
          case 366:men = "E=366 Error en variable";break;
          case 367:men = "E=367 Error en signo";break;
          case 368:men = "E=368 Error en condicion";break;
          case 369:men = "E=369 Error en puertos";break;
          case 370:men = "E=370 Error en signo o en condicion";break;
          case 371:men = "E=371 Error en condicion";break;
          case 372:men = "E=372 Falta parentesis derecho";break;
          case 373:men = "E=373 Error en puertos";break;
          case 374:men = "E=374 Error en alguna instruccion";break;
          case 375:men = "E=375 Error al final de la instruccion";break;
          case 376:men = "E=376 Error en WHILE";break;
          case 377:men = "E=377 Falta parentesis derecho";break;
          case 378:men = "E=378 Error en puertos";break;
          case 379:men = "E=379 Error en sentencia o instruccion";break;
          case 380:men = "E=380 Error al final de la instruccion";break;
          case 381:men = "E=381 Error en WHILE";break;
          case 382:men = "E=382 Error en signo igual";break;
          case 383:men = "E=383 Error en numero hexadecimal";break;
          case 384:men = "E=384 Falta punto y coma";break;
          case 385:men = "E=385 Error en puertos";break;
          case 386:men = "E=386 Error en la condicion";break;
          case 387:men = "E=387 Falta parentesis derecho";break;
          case 388:men = "E=388 Falta parentesis derecho";break;
          case 389:men = "E=389 Error en los puertos";break;
          case 390:men = "E=390 Error en alguna sentencia o instruccion";break;
          case 391:men = "E=391 Error en alguna sentencia o instruccion";break;
          case 392:men = "E=392 Error al final de la instruccion";break;
          case 393:men = "E=393 Error en los puertos";break;
          case 394:men = "E=394 Error en alguna sentencia o instruccion";break;
          case 395:men = "E=395 Error en el cierre de una instruccion";break;
          case 396:men = "E=396 Falta parentesis derecho";break;
          case 397:men = "E=397 Error en los puertos";break;
          case 398:men = "E=398 Error en alguna sentencia o instruccion";break;
          case 399:men = "E=399 Error en alguna sentencia o instruccion";break;
          case 400:men = "E=400 Error al finalizar la sentencia o instruccion";break;
          case 401:men = "E=401       ";break;
          case 402:men = "E=402       ";break;
          case 403:men = "E=403       ";break;
          case 404:men = "E=404       ";break;
          case 405:men = "E=405       ";break;
          case 406:men = "E=406       ";break;
          case 407:men = "E=407       ";break;
          case 408:men = "E=408       ";break;
          case 409:men = "E=409       ";break;
          case 410:men = "E=410       ";break;
          case 411:men = "E=411       ";break;
          case 412:men = "E=412        ";break;
          case 413:men = "E=413        ";break;
          case 414:men = "E=414        ";break;
          case 415:men = "E=415        ";break;
          case 416:men = "E=416        ";break;
          case 417:men = "E=417        ";break;
          case 418:men = "E=418        ";break;
          case 419:men = "E=419        ";break;
          case 420:men = "E=420        ";break;
          case 421:men = "E=421        ";break;
          case 422:men = "E=422        ";break;
          case 423:men = "E=423        ";break;
          case 424:men = "E=424        ";break;
          case 425:men = "E=425        ";break;
          case 426:men = "E=426        ";break;
          case 427:men = "E=427        ";break;
          case 428:men = "E=428        ";break;
          case 429:men = "E=429        ";break;
          case 430:men = "E=430        ";break;
          case 431:men = "E=431        ";break;
          case 432:men = "E=432        ";break;
          case 433:men = "E=433        ";break;
          case 434:men = "E=434        ";break;
          case 435:men = "E=435        ";break;
          case 436:men = "E=436        ";break;
          case 437:men = "E=437        ";break;
          case 438:men = "E=438        ";break;
          case 439:men = "E=439        ";break;
          case 440:men = "E=440        ";break;
          case 441:men = "E=441        ";break;
          case 442:men = "E=442        ";break;
          case 443:men = "E=443        ";break;
          case 444:men = "E=444        ";break;
          case 445:men = "E=445        ";break;
          case 446:men = "E=446        ";break;
          case 447:men = "E=447        ";break;
          case 448:men = "E=448        ";break;
          case 449:men = "E=449        ";break;
          case 450:men = "E=450 Error en el ciclo";break;
          case 451:men = "E=451 Falta un ( ";break;
          case 452:men = "E=452 Falta un )     ";break;
          case 453:men = "E=453 Error al configurar el ciclo";break;
          case 454:men = "E=454 Error al configurar el ciclo";break;
          case 455:men = "E=455 Error al declarar variables globales";break;
          case 456:men = "E=456 Error al configurar el ciclo | setup ";break;
          case 457:men = "E=457 Falta RETARDO";break;
          case 458:men = "E=458 Error al configurar el ciclo";break;
          case 459:men = "E=459 Falta un (";break;
          case 460:men = "E=460 Falta un )";break;
          case 461:men = "E=461 Error al configurar el ciclo  |   Falta ;";break;
          case 462:men = "E=462 Error al configurar el ciclo";break;
          case 463:men = "E=463 Falta un identificador (Nombre) para variable";break;
          case 464:men = "E=464 Error al declarar variable(s)";break;
          case 465:men = "E=465 Falta especificar el tipo de dato";break;
          case 466:men = "E=466 Error al asignar valor a variable";break;
          case 467:men = "E=467 Falta un ; en la declaracion de la varible";break;
          case 468:men = "E=468 NaN | Falta un Número";break;
          case 469:men = "E=469 Falta el identificador";break;
          case 470:men = "E=470 Error al asignar valor a varible";break;
          case 471:men = "E=471 Falta ;";break;
          case 472:men = "E=472 Error al definir el main";break;
          case 473:men = "E=473 Falta el método main";break;
          case 474:men = "E=474 Error en algún puerto";break;
          case 475:men = "E=475 Falta }";break;
          case 476:men = "E=476 Faltan las instrucciones en el método MAIN | Errores en las instrucciones del MAIN";break;
          case 477:men = "E=477 Falta {";break;
          case 478:men = "E=478 Falta el RETARDO";break;
          case 479:men = "E=479 Falta el CICLO";break;
          case 480:men = "E=480 Falta un (";break;
          case 481:men = "E=481 Falta un )";break;
          case 482:men = "E=482 Error al configurar el ciclo";break;
          case 483:men = "E=483 Falta el ciclo";break;
          case 484:men = "E=484 Error al declara un puerto       ";break;
          case 485:men = "E=485 Error al declara un puerto      ";break;
          case 486:men = "E=486 Falta el puerto a configurar";break;
          case 487:men = "E=487 Error al asignar ENTRADA|SALIDA";break;
          case 488:men = "E=488 Error en SALIDA";break;
          case 489:men = "E=489 Error al asignar ENTRADA|SALIDA";break;
          case 490:men = "E=490 Error en ENTRADA";break;
          case 491:men = "E=491 Falta ;";break;
          case 492:men = "E=492 Falta }";break;
          case 493:men = "E=493 Error al configurar puertos |  Falta un puerto para asignar un valor";break;
          case 494:men = "E=494 Error en las instrucciones del SETUP";break;
          case 495:men = "E=495 Falta }  |   Falta RETARDO";break;
          case 496:men = "E=496 Error al declara un puerto";break;
          case 497:men = "E=497 Error al asignar ENTRADA|SALIDA";break;
          case 498:men = "E=498 Falta ;";break;
          case 499:men = "E=499 Falta {";break;
          case 500:men = "E=500 Falta Número";break;
          default: men ="Algo anda mal , ha ocurrido un error";
        }
        return men;
    }

    public String analizaToken(Symbol curToken){
              int analiza = curToken.sym;
              String msn=" ";
              switch(analiza){

                  case 0:msn = "  EOF ";break;
                  case 1:msn = "  error  ";break;
                  case 2:msn = "INT";break;
                  case 3:msn = "FLOAT";break;
                  case 4:msn = "CHAR";break;
                  case 5:msn = "BOOLEAN  ";break;
                  case 6:msn = "CHAR";break;
                  case 7:msn = "FLOAT";break;
                  case 8:msn = "TRUE/FALSE";break;
                  case 9:msn = "COMA ";break;


                  case 10:msn = "TIMEMS";break;
                  case 11:msn = "DELAY";break;
                  case 12:msn = "TMR0";break;
                  case 13:msn = "MAIN";break;
                  case 14:msn = "SETUP";break;
                  case 15:msn = "FUSES";break;
                  case 16:msn = "ENTRADA";break;
                  case 17:msn = "SALIDA";break;
                  case 18:msn = "RETARDO";break;
                  case 19:msn = "CICLO";break;


                  case 20:msn = "PA";break;
                  case 21:msn = "PB";break;
                  case 22:msn = "PC";break;
                  case 23:msn = "PD";break;
                  case 24:msn = "PE";break;
                  case 25:msn = "TA";break;
                  case 26:msn = "TB";break;
                  case 27:msn = "TC";break;
                  case 28:msn = "TD";break;
                  case 29:msn = "TE";break;


                  case 30:msn = "ANSEL";break;
                  case 31:msn = "ANSELH";break;
                  case 32:msn = "TA0";break;
                  case 33:msn = "TA1";break;
                  case 34:msn = "TA2";break;
                  case 35:msn = "TA3";break;
                  case 36:msn = "TA4";break;
                  case 37:msn = "TA5";break;
                  case 38:msn = "TA6";break;
                  case 39:msn = "TA7";break;


                  case 40:msn = "TB0";break;
                  case 41:msn = "TB1";break;
                  case 42:msn = "TB2";break;
                  case 43:msn = "TB3";break;
                  case 44:msn = "TB4";break;
                  case 45:msn = "TB5";break;
                  case 46:msn = "TB6";break;
                  case 47:msn = "TB7";break;
                  case 48:msn = "TC0";break;
                  case 49:msn = "TC1";break;


                  case 50:msn = "TC2";break;
                  case 51:msn = "TC3";break;
                  case 52:msn = "TC4";break;
                  case 53:msn = "TC5";break;
                  case 54:msn = "TC6";break;
                  case 55:msn = "TC7";break;
                  case 56:msn = "TD0";break;
                  case 57:msn = "TD1";break;
                  case 58:msn = "TD2";break;
                  case 59:msn = "TD3";break;



                  case 60:msn = "TD4";break;
                  case 61:msn = "TD5";break;
                  case 62:msn = "TD6";break;
                  case 63:msn = "TD7";break;
                  case 64:msn = "TE0";break;
                  case 65:msn = "TE1";break;
                  case 66:msn = "TE2";break;
                  case 67:msn = "TE3";break;
                  case 68:msn = "PA0";break;
                  case 69:msn = "PA1";break;


                  case 70:msn = "PA2";break;
                  case 71:msn = "PA3";break;
                  case 72:msn = "PA4";break;
                  case 73:msn = "PA5";break;
                  case 74:msn = "PA6";break;
                  case 75:msn = "PA7";break;
                  case 76:msn = "PB0";break;
                  case 77:msn = "PB1";break;
                  case 78:msn = "PB2";break;
                  case 79:msn = "PB3";break;


                  case 80:msn = "PB4";break;
                  case 81:msn = "PB5";break;
                  case 82:msn = "PB6";break;
                  case 83:msn = "PB7";break;
                  case 84:msn = "PC0";break;
                  case 85:msn = "PC1";break;
                  case 86:msn = "PC2";break;
                  case 87:msn = "PC3";break;
                  case 88:msn = "PC4";break;
                  case 89:msn = "PC5";break;



                  case 90:msn = "PC7";break;
                  case 91:msn = "PC7";break;
                  case 92:msn = "PD0";break;
                  case 93:msn = "PD1";break;
                  case 94:msn = "PD2";break;
                  case 95:msn = "PD3";break;
                  case 96:msn = "PD4";break;
                  case 97:msn = "PD5";break;
                  case 98:msn = "PD6";break;
                  case 99:msn = "PD7";break;


                  case 100:msn = "PE0";break;
                  case 101:msn = "PE1";break;
                  case 102:msn = "PE2";break;
                  case 103:msn = "PE3";break;
                  case 104:msn = "ANSEL0";break;
                  case 105:msn = "ANSEL1";break;
                  case 106:msn = "ANSEL2";break;
                  case 107:msn = "ANSEL3";break;
                  case 108:msn = "ANSEL4";break;
                  case 109:msn = "ANSEL5";break;

                  case 110:msn = "ANSEL6";break;
                  case 111:msn = "ANSEL7";break;
                  case 112:msn = "ANSELH0";break;
                  case 113:msn = "ANSELH1";break;
                  case 114:msn = "ANSELH2";break;
                  case 115:msn = "ANSELH3";break;
                  case 116:msn = "ANSELH4";break;
                  case 117:msn = "ANSELH5";break;
                  case 118:msn = "OPTION_REG";break;
                  case 119:msn = "OPTIONREG_INTEDG";break;

                  case 120:msn = "OPTIONREG_PS";break;
                  case 121:msn = "OPTIONREG_T0CS";break;
                  case 122:msn = "OPTIONREG_T0SE";break;
                  case 123:msn = "OPTIONREG_PSA";break;
                  case 124:msn = "OPTIONREG_PS2";break;
                  case 125:msn = "OPTIONREG_PS1";break;
                  case 126:msn = "OPTIONREG_PS0";break;
                  case 127:msn = "OPTIONREG_RBPU";break;
                  case 128:msn = "INTCON";break;
                  case 129:msn = "INTCONGIE";break;

                  case 130:msn = "INTCONPEIE";break;
                  case 131:msn = "INTCONT0IE";break;
                  case 132:msn = "INTCONINTE";break;
                  case 133:msn = "INTCONRBIE";break;
                  case 134:msn = "INTCONT0IF";break;
                  case 135:msn = "INTCONINTF";break;
                  case 136:msn = "INTCONRBIF";break;
                  case 137:msn = "ADCON0_ADCS1";break;
                  case 138:msn = "ADCON0_ADCS0";break;
                  case 139:msn = "ADCON0_CHS3";break;


                  case 140:msn = "ADCON0_CHS2";break;
                  case 141:msn = "ADCON0_CHS1";break;
                  case 142:msn = "ADCON0_CHS0";break;
                  case 143:msn = "ADCON0_GO";break;
                  case 144:msn = "ADCON0_ADON";break;
                  case 145:msn = "ADCON1_ADFM";break;
                  case 146:msn = "ADCON1_VCFG1";break;
                  case 147:msn = "ADCON1_VCFG0";break;
                  case 148:msn = "VOID ";break;
                  case 149:msn = "INTERRUPT";break;

                  case 150:msn = "THEN";break;
                  case 151:msn = "NO";break;
                  case 152:msn = "FIN";break;
                  case 153:msn = "DO";break;
                  case 154:msn = "SWITCH";break;
                  case 155:msn = "OF";break;
                  case 156:msn = "default";break;
                  case 157:msn = "LPAREN/(";break;
                  case 158:msn = "RPAREN/)";break;
                  case 159:msn = "MAS";break;

                  case 160:msn = "MENOS";break;
                  case 161:msn = "DIVISION";break;
                  case 162:msn = "LLLAVE";break;
                  case 163:msn = "RLLAVE";break;
                  case 164:msn = "DOSPUNTOS";break;
                  case 165:msn = "PCOMA";break;
                  case 166:msn = "IGUAL";break;
                  case 167:msn = "==";break;
                  case 168:msn = "TOGGLE";break;
                  case 169:msn = "MAYOR";break;


                  case 170:msn = "MENOR";break;
                  case 171:msn = "MAYORIGUAL";break;
                  case 172:msn = "MENORIGUAL";break;
                  case 173:msn = "AND";break;
                  case 174:msn = "OR";break;
                  case 175:msn = "!=";break;
                  case 176:msn = "TIPOVC/VAR";break;
                  case 177:msn = "RECBITSDER/>>";break;
                  case 178:msn = "RECBITSIZQ/<<";break;
                  case 179:msn = "RETURN";break;

                  case 180:msn = "NUMERO";break;
                  case 181:msn = "ID";break;
                  case 182:msn = "NMETODO";break;
                  case 183:msn = "SI";break;
                  case 184:msn = "CASO";break;
                  case 185:msn = "WHILE";break;
                  case 186:msn = "BINARIO";break;
                  case 187:msn = "HEXACADENA";break;
                  case 188:msn = "FREQ";break;

                  default: msn= "TOKEN DESCONOCIDO"; break;



              }

              return msn;
      }




}
