/* The following code was generated by JFlex 1.4.1 on 14/05/15 08:23 AM */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 14/05/15 08:23 AM from the specification file
 * <tt>C:/Users/postgres/Documents/Mapic/mapic/mapic.flex</tt>
 */
  import java_cup.runtime.Symbol;
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\104\1\105\1\102\2\0\1\105\16\104\4\0\1\105\3\0\1\103"+
    "\2\0\1\101\1\61\1\62\1\0\1\67\1\65\1\70\1\100\1\0"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35\2\2\1\60"+
    "\1\66\1\72\1\73\1\71\2\0\1\21\1\22\1\23\1\24\1\25"+
    "\1\16\1\75\1\1\1\41\2\1\1\40\1\7\1\36\1\53\1\20"+
    "\1\1\1\37\1\10\1\3\1\74\1\47\4\1\1\56\1\0\1\57"+
    "\1\55\1\1\1\0\1\11\1\1\1\45\1\43\1\6\1\54\1\50"+
    "\1\51\1\4\2\1\1\46\1\5\1\12\1\44\1\15\1\1\1\42"+
    "\1\17\1\13\1\14\1\1\1\52\1\1\1\76\1\1\1\63\1\0"+
    "\1\64\1\0\41\104\2\0\4\103\4\0\1\103\2\0\1\104\7\0"+
    "\1\103\4\0\1\103\5\0\27\103\1\0\37\103\1\0\u01ca\103\4\0"+
    "\14\103\16\0\5\103\7\0\1\103\1\0\1\103\21\0\160\104\5\103"+
    "\1\0\2\103\2\0\4\103\10\0\1\103\1\0\3\103\1\0\1\103"+
    "\1\0\24\103\1\0\123\103\1\0\213\103\1\0\5\104\2\0\236\103"+
    "\11\0\46\103\2\0\1\103\7\0\47\103\7\0\1\103\1\0\55\104"+
    "\1\0\1\104\1\0\2\104\1\0\2\104\1\0\1\104\10\0\33\103"+
    "\5\0\3\103\15\0\5\104\6\0\1\103\4\0\13\104\5\0\53\103"+
    "\25\104\12\77\4\0\2\103\1\104\143\103\1\0\1\103\10\104\1\0"+
    "\6\104\2\103\2\104\1\0\4\104\2\103\12\77\3\103\2\0\1\103"+
    "\17\0\1\104\1\103\1\104\36\103\33\104\2\0\131\103\13\104\1\103"+
    "\16\0\12\77\41\103\11\104\2\103\4\0\1\103\5\0\26\103\4\104"+
    "\1\103\11\104\1\103\3\104\1\103\5\104\22\0\31\103\3\104\104\0"+
    "\1\103\1\0\13\103\67\0\33\104\1\0\4\104\66\103\3\104\1\103"+
    "\22\104\1\103\7\104\12\103\2\104\2\0\12\77\1\0\7\103\1\0"+
    "\7\103\1\0\3\104\1\0\10\103\2\0\2\103\2\0\26\103\1\0"+
    "\7\103\1\0\1\103\3\0\4\103\2\0\1\104\1\103\7\104\2\0"+
    "\2\104\2\0\3\104\1\103\10\0\1\104\4\0\2\103\1\0\3\103"+
    "\2\104\2\0\12\77\4\103\7\0\1\103\5\0\3\104\1\0\6\103"+
    "\4\0\2\103\2\0\26\103\1\0\7\103\1\0\2\103\1\0\2\103"+
    "\1\0\2\103\2\0\1\104\1\0\5\104\4\0\2\104\2\0\3\104"+
    "\3\0\1\104\7\0\4\103\1\0\1\103\7\0\12\77\2\104\3\103"+
    "\1\104\13\0\3\104\1\0\11\103\1\0\3\103\1\0\26\103\1\0"+
    "\7\103\1\0\2\103\1\0\5\103\2\0\1\104\1\103\10\104\1\0"+
    "\3\104\1\0\3\104\2\0\1\103\17\0\2\103\2\104\2\0\12\77"+
    "\1\0\1\103\17\0\3\104\1\0\10\103\2\0\2\103\2\0\26\103"+
    "\1\0\7\103\1\0\2\103\1\0\5\103\2\0\1\104\1\103\7\104"+
    "\2\0\2\104\2\0\3\104\10\0\2\104\4\0\2\103\1\0\3\103"+
    "\2\104\2\0\12\77\1\0\1\103\20\0\1\104\1\103\1\0\6\103"+
    "\3\0\3\103\1\0\4\103\3\0\2\103\1\0\1\103\1\0\2\103"+
    "\3\0\2\103\3\0\3\103\3\0\14\103\4\0\5\104\3\0\3\104"+
    "\1\0\4\104\2\0\1\103\6\0\1\104\16\0\12\77\11\0\1\103"+
    "\7\0\3\104\1\0\10\103\1\0\3\103\1\0\27\103\1\0\12\103"+
    "\1\0\5\103\3\0\1\103\7\104\1\0\3\104\1\0\4\104\7\0"+
    "\2\104\1\0\2\103\6\0\2\103\2\104\2\0\12\77\22\0\2\104"+
    "\1\0\10\103\1\0\3\103\1\0\27\103\1\0\12\103\1\0\5\103"+
    "\2\0\1\104\1\103\7\104\1\0\3\104\1\0\4\104\7\0\2\104"+
    "\7\0\1\103\1\0\2\103\2\104\2\0\12\77\1\0\2\103\17\0"+
    "\2\104\1\0\10\103\1\0\3\103\1\0\51\103\2\0\1\103\7\104"+
    "\1\0\3\104\1\0\4\104\1\103\10\0\1\104\10\0\2\103\2\104"+
    "\2\0\12\77\12\0\6\103\2\0\2\104\1\0\22\103\3\0\30\103"+
    "\1\0\11\103\1\0\1\103\2\0\7\103\3\0\1\104\4\0\6\104"+
    "\1\0\1\104\1\0\10\104\22\0\2\104\15\0\60\103\1\104\2\103"+
    "\7\104\4\0\10\103\10\104\1\0\12\77\47\0\2\103\1\0\1\103"+
    "\2\0\2\103\1\0\1\103\2\0\1\103\6\0\4\103\1\0\7\103"+
    "\1\0\3\103\1\0\1\103\1\0\1\103\2\0\2\103\1\0\4\103"+
    "\1\104\2\103\6\104\1\0\2\104\1\103\2\0\5\103\1\0\1\103"+
    "\1\0\6\104\2\0\12\77\2\0\4\103\40\0\1\103\27\0\2\104"+
    "\6\0\12\77\13\0\1\104\1\0\1\104\1\0\1\104\4\0\2\104"+
    "\10\103\1\0\44\103\4\0\24\104\1\0\2\104\5\103\13\104\1\0"+
    "\44\104\11\0\1\104\71\0\53\103\24\104\1\103\12\77\6\0\6\103"+
    "\4\104\4\103\3\104\1\103\3\104\2\103\7\104\3\103\4\104\15\103"+
    "\14\104\1\103\1\104\12\77\4\104\2\0\46\103\1\0\1\103\5\0"+
    "\1\103\2\0\53\103\1\0\u014d\103\1\0\4\103\2\0\7\103\1\0"+
    "\1\103\1\0\4\103\2\0\51\103\1\0\4\103\2\0\41\103\1\0"+
    "\4\103\2\0\7\103\1\0\1\103\1\0\4\103\2\0\17\103\1\0"+
    "\71\103\1\0\4\103\2\0\103\103\2\0\3\104\40\0\20\103\20\0"+
    "\125\103\14\0\u026c\103\2\0\21\103\1\0\32\103\5\0\113\103\3\0"+
    "\3\103\17\0\15\103\1\0\4\103\3\104\13\0\22\103\3\104\13\0"+
    "\22\103\2\104\14\0\15\103\1\0\3\103\1\0\2\104\14\0\64\103"+
    "\40\104\3\0\1\103\3\0\2\103\1\104\2\0\12\77\41\0\3\104"+
    "\2\0\12\77\6\0\130\103\10\0\51\103\1\104\1\103\5\0\106\103"+
    "\12\0\35\103\3\0\14\104\4\0\14\104\12\0\12\77\36\103\2\0"+
    "\5\103\13\0\54\103\4\0\21\104\7\103\2\104\6\0\12\77\46\0"+
    "\27\103\5\104\4\0\65\103\12\104\1\0\35\104\2\0\1\104\12\77"+
    "\6\0\12\77\15\0\1\103\130\0\5\104\57\103\21\104\7\103\4\0"+
    "\12\77\21\0\11\104\14\0\3\104\36\103\15\104\2\103\12\77\54\103"+
    "\16\104\14\0\44\103\24\104\10\0\12\77\3\0\3\103\12\77\44\103"+
    "\122\0\3\104\1\0\25\104\4\103\1\104\4\103\3\104\2\103\11\0"+
    "\300\103\47\104\25\0\4\104\u0116\103\2\0\6\103\2\0\46\103\2\0"+
    "\6\103\2\0\10\103\1\0\1\103\1\0\1\103\1\0\1\103\1\0"+
    "\37\103\2\0\65\103\1\0\7\103\1\0\1\103\3\0\3\103\1\0"+
    "\7\103\3\0\4\103\2\0\6\103\4\0\15\103\5\0\3\103\1\0"+
    "\7\103\16\0\5\104\32\0\5\104\20\0\2\103\23\0\1\103\13\0"+
    "\5\104\5\0\6\104\1\0\1\103\15\0\1\103\20\0\15\103\3\0"+
    "\33\103\25\0\15\104\4\0\1\104\3\0\14\104\21\0\1\103\4\0"+
    "\1\103\2\0\12\103\1\0\1\103\3\0\5\103\6\0\1\103\1\0"+
    "\1\103\1\0\1\103\1\0\4\103\1\0\13\103\2\0\4\103\5\0"+
    "\5\103\4\0\1\103\21\0\51\103\u0a77\0\57\103\1\0\57\103\1\0"+
    "\205\103\6\0\4\103\3\104\2\103\14\0\46\103\1\0\1\103\5\0"+
    "\1\103\2\0\70\103\7\0\1\103\17\0\1\104\27\103\11\0\7\103"+
    "\1\0\7\103\1\0\7\103\1\0\7\103\1\0\7\103\1\0\7\103"+
    "\1\0\7\103\1\0\7\103\1\0\40\104\57\0\1\103\u01d5\0\3\103"+
    "\31\0\11\103\6\104\1\0\5\103\2\0\5\103\4\0\126\103\2\0"+
    "\2\104\2\0\3\103\1\0\132\103\1\0\4\103\5\0\51\103\3\0"+
    "\136\103\21\0\33\103\65\0\20\103\u0200\0\u19b6\103\112\0\u51cd\103\63\0"+
    "\u048d\103\103\0\56\103\2\0\u010d\103\3\0\20\103\12\77\2\103\24\0"+
    "\57\103\1\104\4\0\12\104\1\0\31\103\7\0\1\104\120\103\2\104"+
    "\45\0\11\103\2\0\147\103\2\0\4\103\1\0\4\103\14\0\13\103"+
    "\115\0\12\103\1\104\3\103\1\104\4\103\1\104\27\103\5\104\20\0"+
    "\1\103\7\0\64\103\14\0\2\104\62\103\21\104\13\0\12\77\6\0"+
    "\22\104\6\103\3\0\1\103\4\0\12\77\34\103\10\104\2\0\27\103"+
    "\15\104\14\0\35\103\3\0\4\104\57\103\16\104\16\0\1\103\12\77"+
    "\46\0\51\103\16\104\11\0\3\103\1\104\10\103\2\104\2\0\12\77"+
    "\6\0\27\103\3\0\1\103\1\104\4\0\60\103\1\104\1\103\3\104"+
    "\2\103\2\104\5\103\2\104\1\103\1\104\1\103\30\0\3\103\2\0"+
    "\13\103\5\104\2\0\3\103\2\104\12\0\6\103\2\0\6\103\2\0"+
    "\6\103\11\0\7\103\1\0\7\103\221\0\43\103\10\104\1\0\2\104"+
    "\2\0\12\77\6\0\u2ba4\103\14\0\27\103\4\0\61\103\u2104\0\u016e\103"+
    "\2\0\152\103\46\0\7\103\14\0\5\103\5\0\1\103\1\104\12\103"+
    "\1\0\15\103\1\0\5\103\1\0\1\103\1\0\2\103\1\0\2\103"+
    "\1\0\154\103\41\0\u016b\103\22\0\100\103\2\0\66\103\50\0\15\103"+
    "\3\0\20\104\20\0\7\104\14\0\2\103\30\0\3\103\31\0\1\103"+
    "\6\0\5\103\1\0\207\103\2\0\1\104\4\0\1\103\13\0\12\77"+
    "\7\0\32\103\4\0\1\103\1\0\32\103\13\0\131\103\3\0\6\103"+
    "\2\0\6\103\2\0\6\103\2\0\3\103\3\0\2\103\3\0\2\103"+
    "\22\0\3\104\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\22\2\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\1\1\23\1\24\1\0"+
    "\1\2\1\25\1\26\1\27\1\30\1\31\1\2\1\32"+
    "\2\2\1\33\6\2\1\34\1\35\1\36\1\37\1\40"+
    "\10\2\1\41\1\2\1\42\6\2\1\43\1\44\1\45"+
    "\1\46\1\47\1\0\1\50\1\2\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\61\1\62\1\63"+
    "\1\64\1\65\1\66\1\67\1\70\1\71\1\72\1\73"+
    "\1\74\1\75\1\76\1\77\1\100\1\101\1\102\1\103"+
    "\1\104\1\105\1\106\1\107\1\110\1\111\1\112\1\113"+
    "\1\114\6\2\1\115\3\2\1\116\1\117\1\120\1\121"+
    "\1\122\1\123\1\124\1\125\1\126\1\127\1\130\1\131"+
    "\1\132\1\133\1\134\1\135\1\136\1\137\1\140\1\141"+
    "\1\142\1\143\1\144\1\145\1\146\1\147\1\150\1\151"+
    "\1\152\1\153\1\154\1\155\1\156\1\157\1\160\1\161"+
    "\1\2\1\162\13\2\1\163\2\2\1\164\1\2\1\165"+
    "\1\2\1\166\1\167\10\2\1\170\1\171\1\2\1\172"+
    "\3\2\1\173\3\2\1\174\1\2\1\175\2\2\1\176"+
    "\1\2\1\177\4\2\1\200\1\201\1\202\1\203\1\204"+
    "\6\2\1\205\1\206\1\207\1\210\1\211\1\212";

  private static int [] zzUnpackAction() {
    int [] result = new int[240];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\106\0\214\0\322\0\u0118\0\u015e\0\u01a4\0\u01ea"+
    "\0\u0230\0\u0276\0\u02bc\0\u0302\0\u0348\0\u038e\0\u03d4\0\u041a"+
    "\0\u0460\0\u04a6\0\u04ec\0\u0532\0\u0578\0\u05be\0\106\0\106"+
    "\0\106\0\106\0\106\0\106\0\106\0\106\0\106\0\106"+
    "\0\106\0\106\0\u0604\0\u064a\0\u0690\0\u06d6\0\u071c\0\u0762"+
    "\0\u07a8\0\u07ee\0\u0834\0\u087a\0\u08c0\0\u0906\0\u094c\0\u0992"+
    "\0\u09d8\0\u0a1e\0\u0a64\0\214\0\u0aaa\0\u0af0\0\u0b36\0\u0b7c"+
    "\0\u0bc2\0\u0c08\0\u0c4e\0\u0c94\0\u0cda\0\u0d20\0\u0d66\0\u0dac"+
    "\0\u0df2\0\u0e38\0\u0e7e\0\u0ec4\0\u0f0a\0\u0f50\0\u0f96\0\214"+
    "\0\u0fdc\0\214\0\u1022\0\u1068\0\u10ae\0\u10f4\0\u113a\0\u1180"+
    "\0\214\0\214\0\106\0\106\0\106\0\u11c6\0\u07a8\0\u120c"+
    "\0\214\0\214\0\214\0\214\0\214\0\214\0\214\0\214"+
    "\0\214\0\214\0\214\0\214\0\214\0\214\0\214\0\214"+
    "\0\214\0\214\0\214\0\214\0\214\0\214\0\214\0\214"+
    "\0\214\0\214\0\214\0\214\0\214\0\214\0\214\0\214"+
    "\0\214\0\214\0\214\0\214\0\u1252\0\u1298\0\u12de\0\u1324"+
    "\0\u136a\0\u13b0\0\214\0\u13f6\0\u143c\0\u1482\0\214\0\214"+
    "\0\214\0\214\0\214\0\214\0\214\0\214\0\214\0\214"+
    "\0\214\0\214\0\214\0\214\0\214\0\214\0\214\0\214"+
    "\0\214\0\214\0\214\0\214\0\214\0\214\0\214\0\214"+
    "\0\214\0\214\0\214\0\214\0\214\0\214\0\214\0\214"+
    "\0\214\0\214\0\u14c8\0\214\0\u150e\0\u1554\0\u159a\0\u15e0"+
    "\0\u1626\0\u166c\0\u16b2\0\u16f8\0\u173e\0\u1784\0\u17ca\0\214"+
    "\0\u1810\0\u1856\0\106\0\u189c\0\214\0\u18e2\0\214\0\214"+
    "\0\u1928\0\u196e\0\u19b4\0\u19fa\0\u1a40\0\u1a86\0\u1acc\0\u1b12"+
    "\0\214\0\214\0\u1b58\0\214\0\u1b9e\0\u1be4\0\u1c2a\0\214"+
    "\0\u1c70\0\u1cb6\0\u1cfc\0\214\0\u1d42\0\214\0\u1d88\0\u1dce"+
    "\0\214\0\u1e14\0\214\0\u1e5a\0\u1ea0\0\u1ee6\0\u1f2c\0\214"+
    "\0\214\0\214\0\214\0\214\0\u1f72\0\u1fb8\0\u1ffe\0\u2044"+
    "\0\u208a\0\u20d0\0\214\0\214\0\214\0\214\0\214\0\214";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[240];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\3\3\1\6\1\7\5\3"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\10\4\1\20\1\21\1\3\1\22\1\3\1\23\3\3"+
    "\1\24\2\3\1\25\1\26\1\3\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\3\3\1\4\1\2\1\46"+
    "\1\47\1\50\1\2\1\47\107\0\54\3\17\0\3\3"+
    "\1\50\3\0\2\50\3\0\1\4\23\0\10\4\41\0"+
    "\1\4\1\51\6\0\3\3\1\52\14\3\1\53\1\54"+
    "\1\55\1\56\1\57\11\3\1\60\4\3\1\61\4\3"+
    "\1\62\3\3\17\0\3\3\1\50\3\0\2\50\2\0"+
    "\10\3\1\63\43\3\17\0\3\3\1\50\3\0\2\50"+
    "\2\0\3\3\1\64\1\3\1\65\12\3\1\66\33\3"+
    "\17\0\3\3\1\50\3\0\2\50\2\0\3\3\1\67"+
    "\7\3\1\70\4\3\1\71\33\3\17\0\3\3\1\50"+
    "\3\0\2\50\2\0\51\3\1\72\2\3\17\0\3\3"+
    "\1\50\3\0\2\50\2\0\20\3\1\73\1\74\1\75"+
    "\1\76\1\77\16\3\1\100\10\3\17\0\3\3\1\50"+
    "\3\0\2\50\2\0\35\3\1\101\3\3\1\102\12\3"+
    "\17\0\3\3\1\50\3\0\2\50\2\0\43\3\1\103"+
    "\10\3\17\0\3\3\1\50\3\0\2\50\2\0\3\3"+
    "\1\104\4\3\1\105\32\3\1\106\4\3\1\107\3\3"+
    "\17\0\3\3\1\50\3\0\2\50\2\0\43\3\1\110"+
    "\10\3\17\0\3\3\1\50\3\0\2\50\2\0\35\3"+
    "\1\111\16\3\17\0\3\3\1\50\3\0\2\50\2\0"+
    "\43\3\1\112\10\3\17\0\3\3\1\50\3\0\2\50"+
    "\2\0\5\3\1\113\46\3\17\0\3\3\1\50\3\0"+
    "\2\50\2\0\35\3\1\114\16\3\17\0\3\3\1\50"+
    "\3\0\2\50\2\0\5\3\1\115\46\3\17\0\3\3"+
    "\1\50\3\0\2\50\2\0\10\3\1\116\32\3\1\117"+
    "\10\3\17\0\3\3\1\50\3\0\2\50\2\0\50\3"+
    "\1\120\3\3\17\0\3\3\1\50\3\0\2\50\2\0"+
    "\36\3\1\121\14\3\1\122\17\0\3\3\1\50\3\0"+
    "\2\50\74\0\1\123\105\0\1\124\105\0\1\125\12\0"+
    "\102\126\1\0\3\126\102\0\1\47\2\0\1\47\1\0"+
    "\54\50\17\0\4\50\3\0\2\50\3\0\1\127\23\0"+
    "\10\127\41\0\1\127\7\0\4\3\1\130\47\3\17\0"+
    "\3\3\1\50\3\0\2\50\2\0\25\3\1\131\1\132"+
    "\1\133\1\134\1\135\1\136\1\137\1\140\17\3\17\0"+
    "\3\3\1\50\3\0\2\50\2\0\25\3\1\141\1\142"+
    "\1\143\1\144\1\145\1\146\1\147\1\150\17\3\17\0"+
    "\3\3\1\50\3\0\2\50\2\0\25\3\1\151\1\152"+
    "\1\153\1\154\1\155\1\156\1\157\1\160\17\3\17\0"+
    "\3\3\1\50\3\0\2\50\2\0\25\3\1\161\1\162"+
    "\1\163\1\164\1\165\1\166\1\167\1\170\17\3\17\0"+
    "\3\3\1\50\3\0\2\50\2\0\25\3\1\171\1\172"+
    "\1\173\1\174\23\3\17\0\3\3\1\50\3\0\2\50"+
    "\2\0\54\3\17\0\1\175\2\3\1\50\3\0\2\50"+
    "\2\0\47\3\1\176\4\3\17\0\3\3\1\50\3\0"+
    "\2\50\2\0\5\3\1\177\46\3\17\0\3\3\1\50"+
    "\3\0\2\50\2\0\3\3\1\200\50\3\17\0\3\3"+
    "\1\50\3\0\2\50\2\0\12\3\1\201\41\3\17\0"+
    "\3\3\1\50\3\0\2\50\2\0\37\3\1\202\14\3"+
    "\17\0\3\3\1\50\3\0\2\50\2\0\11\3\1\203"+
    "\42\3\17\0\3\3\1\50\3\0\2\50\2\0\16\3"+
    "\1\204\35\3\17\0\3\3\1\50\3\0\2\50\2\0"+
    "\37\3\1\205\14\3\17\0\3\3\1\50\3\0\2\50"+
    "\2\0\3\3\1\206\50\3\17\0\3\3\1\50\3\0"+
    "\2\50\2\0\25\3\1\207\1\210\1\211\1\212\1\213"+
    "\1\214\1\215\1\216\17\3\17\0\3\3\1\50\3\0"+
    "\2\50\2\0\25\3\1\217\1\220\1\221\1\222\1\223"+
    "\1\224\1\225\1\226\17\3\17\0\3\3\1\50\3\0"+
    "\2\50\2\0\25\3\1\227\1\230\1\231\1\232\1\233"+
    "\1\234\1\235\1\236\17\3\17\0\3\3\1\50\3\0"+
    "\2\50\2\0\25\3\1\237\1\240\1\241\1\242\1\243"+
    "\1\244\1\245\1\246\17\3\17\0\3\3\1\50\3\0"+
    "\2\50\2\0\25\3\1\247\1\250\1\251\1\252\23\3"+
    "\17\0\3\3\1\50\3\0\2\50\2\0\3\3\1\253"+
    "\50\3\17\0\3\3\1\50\3\0\2\50\2\0\23\3"+
    "\1\254\30\3\17\0\3\3\1\50\3\0\2\50\2\0"+
    "\41\3\1\255\12\3\17\0\3\3\1\50\3\0\2\50"+
    "\2\0\43\3\1\256\10\3\17\0\3\3\1\50\3\0"+
    "\2\50\2\0\44\3\1\257\7\3\17\0\3\3\1\50"+
    "\3\0\2\50\2\0\16\3\1\260\35\3\17\0\3\3"+
    "\1\50\3\0\2\50\2\0\11\3\1\261\42\3\17\0"+
    "\3\3\1\50\3\0\2\50\2\0\10\3\1\262\43\3"+
    "\17\0\3\3\1\50\3\0\2\50\2\0\2\3\1\263"+
    "\51\3\17\0\3\3\1\50\3\0\2\50\2\0\10\3"+
    "\1\264\1\3\1\265\41\3\17\0\3\3\1\50\3\0"+
    "\2\50\2\0\2\3\1\266\51\3\17\0\3\3\1\50"+
    "\3\0\2\50\2\0\53\3\1\267\17\0\3\3\1\50"+
    "\3\0\2\50\2\0\41\3\1\270\12\3\17\0\3\3"+
    "\1\50\3\0\2\50\2\0\3\3\1\271\50\3\17\0"+
    "\3\3\1\50\3\0\2\50\2\0\3\3\1\272\50\3"+
    "\17\0\3\3\1\50\3\0\2\50\102\0\1\273\5\0"+
    "\5\3\1\274\46\3\17\0\3\3\1\50\3\0\2\50"+
    "\2\0\24\3\1\275\27\3\17\0\3\3\1\50\3\0"+
    "\2\50\2\0\47\3\1\276\4\3\17\0\3\3\1\50"+
    "\3\0\2\50\2\0\11\3\1\277\42\3\17\0\3\3"+
    "\1\50\3\0\2\50\2\0\11\3\1\300\42\3\17\0"+
    "\3\3\1\50\3\0\2\50\2\0\13\3\1\301\40\3"+
    "\17\0\3\3\1\50\3\0\2\50\2\0\40\3\1\302"+
    "\13\3\17\0\3\3\1\50\3\0\2\50\2\0\5\3"+
    "\1\303\46\3\17\0\3\3\1\50\3\0\2\50\2\0"+
    "\7\3\1\175\44\3\17\0\3\3\1\50\3\0\2\50"+
    "\2\0\12\3\1\304\41\3\17\0\3\3\1\50\3\0"+
    "\2\50\2\0\11\3\1\305\42\3\17\0\3\3\1\50"+
    "\3\0\2\50\2\0\10\3\1\306\43\3\17\0\3\3"+
    "\1\50\3\0\2\50\2\0\45\3\1\307\6\3\17\0"+
    "\3\3\1\50\3\0\2\50\2\0\45\3\1\310\6\3"+
    "\17\0\3\3\1\50\3\0\2\50\2\0\43\3\1\311"+
    "\10\3\17\0\3\3\1\50\3\0\2\50\2\0\16\3"+
    "\1\270\35\3\17\0\3\3\1\50\3\0\2\50\2\0"+
    "\41\3\1\312\12\3\17\0\3\3\1\50\3\0\2\50"+
    "\2\0\36\3\1\313\15\3\17\0\3\3\1\50\3\0"+
    "\2\50\2\0\45\3\1\314\6\3\17\0\3\3\1\50"+
    "\3\0\2\50\2\0\10\3\1\315\43\3\17\0\3\3"+
    "\1\50\3\0\2\50\2\0\24\3\1\316\27\3\17\0"+
    "\3\3\1\50\3\0\2\50\2\0\10\3\1\317\43\3"+
    "\17\0\3\3\1\50\3\0\2\50\2\0\42\3\1\320"+
    "\11\3\17\0\3\3\1\50\3\0\2\50\2\0\45\3"+
    "\1\321\6\3\17\0\3\3\1\50\3\0\2\50\2\0"+
    "\6\3\1\322\45\3\17\0\3\3\1\50\3\0\2\50"+
    "\2\0\45\3\1\323\6\3\17\0\3\3\1\50\3\0"+
    "\2\50\2\0\14\3\1\324\37\3\17\0\3\3\1\50"+
    "\3\0\2\50\2\0\23\3\1\325\30\3\17\0\3\3"+
    "\1\50\3\0\2\50\2\0\16\3\1\326\35\3\17\0"+
    "\3\3\1\50\3\0\2\50\2\0\44\3\1\327\7\3"+
    "\17\0\3\3\1\50\3\0\2\50\2\0\12\3\1\330"+
    "\41\3\17\0\3\3\1\50\3\0\2\50\2\0\54\3"+
    "\17\0\2\3\1\331\1\50\3\0\2\50\2\0\5\3"+
    "\1\332\46\3\17\0\3\3\1\50\3\0\2\50\2\0"+
    "\43\3\1\333\10\3\17\0\3\3\1\50\3\0\2\50"+
    "\2\0\20\3\1\334\33\3\17\0\3\3\1\50\3\0"+
    "\2\50\2\0\41\3\1\335\12\3\17\0\3\3\1\50"+
    "\3\0\2\50\2\0\54\3\17\0\1\3\1\336\1\3"+
    "\1\50\3\0\2\50\2\0\13\3\1\337\40\3\17\0"+
    "\3\3\1\50\3\0\2\50\2\0\5\3\1\340\46\3"+
    "\17\0\3\3\1\50\3\0\2\50\2\0\7\3\1\341"+
    "\44\3\17\0\3\3\1\50\3\0\2\50\2\0\5\3"+
    "\1\342\46\3\17\0\3\3\1\50\3\0\2\50\2\0"+
    "\20\3\1\343\33\3\17\0\3\3\1\50\3\0\2\50"+
    "\2\0\50\3\1\344\3\3\17\0\3\3\1\50\3\0"+
    "\2\50\2\0\5\3\1\345\46\3\17\0\3\3\1\50"+
    "\3\0\2\50\2\0\10\3\1\346\43\3\17\0\3\3"+
    "\1\50\3\0\2\50\2\0\23\3\1\347\30\3\17\0"+
    "\3\3\1\50\3\0\2\50\2\0\42\3\1\350\11\3"+
    "\17\0\3\3\1\50\3\0\2\50\2\0\24\3\1\351"+
    "\27\3\17\0\3\3\1\50\3\0\2\50\2\0\45\3"+
    "\1\352\6\3\17\0\3\3\1\50\3\0\2\50\2\0"+
    "\41\3\1\353\12\3\17\0\3\3\1\50\3\0\2\50"+
    "\2\0\11\3\1\354\42\3\17\0\3\3\1\50\3\0"+
    "\2\50\2\0\20\3\1\355\33\3\17\0\3\3\1\50"+
    "\3\0\2\50\2\0\43\3\1\356\10\3\17\0\3\3"+
    "\1\50\3\0\2\50\2\0\36\3\1\357\15\3\17\0"+
    "\3\3\1\50\3\0\2\50\2\0\12\3\1\360\41\3"+
    "\17\0\3\3\1\50\3\0\2\50\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8470];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\24\1\14\11\6\1\1\0\51\1\3\11"+
    "\1\0\144\1\1\11\65\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[240];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

	int lineaActual=1;
	private static int actualEtq=0;
	
	public int linea(){ return yyline+1; }
	public int columna(){ return yycolumn+1; }
	
	private static String nuevaEtq(){
		return "etqL"+(++actualEtq);
	}

   	  private Symbol symbol(int type){
	  return new Symbol(type, yyline, yycolumn);
	}
	private Symbol symbol(int type, Object value){
	  return new Symbol(type, yyline, yycolumn, value);
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2306) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 60: 
          { return symbol(sym.TC,new String("\tTRISCbits.TRISC3"));
          }
        case 139: break;
        case 99: 
          { return symbol(sym.PC5,new String("\tPORTCbits.RC5"));
          }
        case 140: break;
        case 49: 
          { return symbol(sym.TA,new String("\tTRISBbits.TRISB0"));
          }
        case 141: break;
        case 4: 
          { return symbol(sym.CIRCUN);
          }
        case 142: break;
        case 120: 
          { return symbol(sym.CASO,nuevaEtq());
          }
        case 143: break;
        case 78: 
          { return symbol(sym.PA0,new String("\tPORTAbits.RA0"));
          }
        case 144: break;
        case 113: 
          { return symbol(sym.PE3,new String("\tPORTEbits.RE3"));
          }
        case 145: break;
        case 67: 
          { return symbol(sym.TD,new String("\tTRISDbits.TRISD2"));
          }
        case 146: break;
        case 41: 
          { return symbol(sym.TA,new String("\tTRISAbits.TRISA0"));
          }
        case 147: break;
        case 132: 
          { return symbol(sym.SWITCH);
          }
        case 148: break;
        case 106: 
          { return symbol(sym.PD4,new String("\tPORTDbits.RD4"));
          }
        case 149: break;
        case 54: 
          { return symbol(sym.TA,new String("\tTRISBbits.TRISB5"));
          }
        case 150: break;
        case 35: 
          { return symbol(sym.OR);
          }
        case 151: break;
        case 8: 
          { return symbol(sym.LPAREN);
          }
        case 152: break;
        case 90: 
          { return symbol(sym.PB4,new String("\tPORTBbits.RB4"));
          }
        case 153: break;
        case 72: 
          { return symbol(sym.TD,new String("\tTRISDbits.TRISD7"));
          }
        case 154: break;
        case 33: 
          { return  symbol(sym.DO);
          }
        case 155: break;
        case 46: 
          { return symbol(sym.TA,new String("\tTRISAbits.TRISA5"));
          }
        case 156: break;
        case 83: 
          { return symbol(sym.PA5,new String("\tPORTAbits.RA5"));
          }
        case 157: break;
        case 126: 
          { return symbol(sym.ARRAY);
          }
        case 158: break;
        case 29: 
          { return symbol(sym.PB,new String("\tPORTB"));
          }
        case 159: break;
        case 34: 
          { return symbol(sym.NO);
          }
        case 160: break;
        case 128: 
          { return symbol(sym.WHILE ,nuevaEtq());
          }
        case 161: break;
        case 97: 
          { return symbol(sym.PC3,new String("\tPORTCbits.RC3"));
          }
        case 162: break;
        case 73: 
          { return symbol(sym.TE,new String("\tTRISEbits.TRISE0"));
          }
        case 163: break;
        case 31: 
          { return symbol(sym.PD,new String("\tPORTD"));
          }
        case 164: break;
        case 14: 
          { return symbol(sym.MAS);
          }
        case 165: break;
        case 59: 
          { return symbol(sym.TC,new String("\tTRISCbits.TRISC2"));
          }
        case 166: break;
        case 123: 
          { return symbol(sym.VOID,new String("\n\tvoid  "));
          }
        case 167: break;
        case 111: 
          { return symbol(sym.PE1,new String("\tPORTEbits.RE1"));
          }
        case 168: break;
        case 3: 
          { return symbol(sym.NUMERO, new Integer(yytext()));
          }
        case 169: break;
        case 66: 
          { return symbol(sym.TD,new String("\tTRISDbits.TRISD1"));
          }
        case 170: break;
        case 64: 
          { return symbol(sym.TC,new String("\tTRISCbits.TRISC7"));
          }
        case 171: break;
        case 104: 
          { return symbol(sym.PD2,new String("\tPORTDbits.RD2"));
          }
        case 172: break;
        case 114: 
          { return symbol(sym.AND);
          }
        case 173: break;
        case 88: 
          { return symbol(sym.PB2,new String("\tPORTBbits.RB2"));
          }
        case 174: break;
        case 40: 
          { return symbol(sym.NUMREAL);
          }
        case 175: break;
        case 12: 
          { return symbol(sym.COMA);
          }
        case 176: break;
        case 53: 
          { return symbol(sym.TA,new String("\tTRISBbits.TRISB4"));
          }
        case 177: break;
        case 11: 
          { return symbol(sym.RLLAVE);
          }
        case 178: break;
        case 81: 
          { return symbol(sym.PA3,new String("\tPORTAbits.RA3"));
          }
        case 179: break;
        case 71: 
          { return symbol(sym.TD,new String("\tTRISDbits.TRISD6"));
          }
        case 180: break;
        case 45: 
          { return symbol(sym.TA,new String("\tTRISAbits.TRISA4"));
          }
        case 181: break;
        case 26: 
          { return symbol(sym.TO);
          }
        case 182: break;
        case 127: 
          { return symbol(sym.CICLO,new String("\n\n\tvoid loop()"));
          }
        case 183: break;
        case 95: 
          { return symbol(sym.PC1,new String("\tPORTCbits.RC1"));
          }
        case 184: break;
        case 22: 
          { return symbol(sym.TB,new String("\tTRISB"));
          }
        case 185: break;
        case 109: 
          { return symbol(sym.PD7,new String("\tPORTDbits.RD7"));
          }
        case 186: break;
        case 93: 
          { return symbol(sym.PB7,new String("\tPORTBbits.RB7"));
          }
        case 187: break;
        case 24: 
          { return symbol(sym.TD,new String("\tTRISD"));
          }
        case 188: break;
        case 27: 
          { return symbol(sym.SI,nuevaEtq());
          }
        case 189: break;
        case 130: 
          { return symbol(sym.TOGGLE,new String("!"));
          }
        case 190: break;
        case 15: 
          { return symbol(sym.MENOS);
          }
        case 191: break;
        case 58: 
          { return symbol(sym.TC,new String("\tTRISCbits.TRISC1"));
          }
        case 192: break;
        case 1: 
          { System.out.println("Error léxico en línea "+lineaActual+":-"+yytext()+"-");
          }
        case 193: break;
        case 17: 
          { return symbol(sym.MENOR);
          }
        case 194: break;
        case 102: 
          { return symbol(sym.PD0,new String("\tPORTDbits.RD0"));
          }
        case 195: break;
        case 86: 
          { return symbol(sym.PB0,new String("\tPORTBbits.RB0"));
          }
        case 196: break;
        case 100: 
          { return symbol(sym.PC6,new String("\tPORTCbits.RC6"));
          }
        case 197: break;
        case 65: 
          { return symbol(sym.TD,new String("\tTRISDbits.TRISD0"));
          }
        case 198: break;
        case 63: 
          { return symbol(sym.TC,new String("\tTRISCbits.TRISC6"));
          }
        case 199: break;
        case 79: 
          { return symbol(sym.PA1,new String("\tPORTAbits.RA1"));
          }
        case 200: break;
        case 52: 
          { return symbol(sym.TA,new String("\tTRISBbits.TRISB3"));
          }
        case 201: break;
        case 36: 
          { return symbol(sym.OF);
          }
        case 202: break;
        case 134: 
          { return symbol(sym.BOOLEAN);
          }
        case 203: break;
        case 70: 
          { return symbol(sym.TD,new String("\tTRISDbits.TRISD5"));
          }
        case 204: break;
        case 6: 
          { return symbol(sym.RCORCH);
          }
        case 205: break;
        case 10: 
          { return symbol(sym.LLLAVE);
          }
        case 206: break;
        case 44: 
          { return symbol(sym.TA,new String("\tTRISAbits.TRISA3"));
          }
        case 207: break;
        case 107: 
          { return symbol(sym.PD5,new String("\tPORTDbits.RD5"));
          }
        case 208: break;
        case 91: 
          { return symbol(sym.PB5,new String("\tPORTBbits.RB5"));
          }
        case 209: break;
        case 133: 
          { return symbol(sym.POINTER);
          }
        case 210: break;
        case 84: 
          { return symbol(sym.PA6,new String("\tPORTAbits.RA6"));
          }
        case 211: break;
        case 7: 
          { return symbol(sym.DOSPUNTOS);
          }
        case 212: break;
        case 57: 
          { return symbol(sym.TC,new String("\tTRISCbits.TRISC0"));
          }
        case 213: break;
        case 125: 
          { return symbol(sym.FUSES,new String("#include <xc.h>\n"
								                + "// CONFIG1\n" 
								                +"#pragma config FOSC = INTRC_NOCLKOUT// Oscillator Selection bits (INTOSC oscillator: CLKOUT function on RA6/OSC2/CLKOUT pin, I/O function on RA7/OSC1/CLKIN)\n" 
								                +"#pragma config WDTE = OFF       // Watchdog Timer Enable bit (WDT disabled and can be enabled by SWDTEN bit of the WDTCON register)\n"
								                +"#pragma config PWRTE = OFF      // Power-up Timer Enable bit (PWRT disabled)\n"
								                +"#pragma config MCLRE = OFF      // RE3/MCLR pin function select bit (RE3/MCLR pin function is digital input, MCLR internally tied to VDD)\n" 
								                +"#pragma config CP = OFF         // Code Protection bit (Program memory code protection is disabled)\n"
								                +"#pragma config CPD = OFF        // Data Code Protection bit (Data memory code protection is disabled)\n"
								                +"#pragma config BOREN = OFF      // Brown Out Reset Selection bits (BOR disabled)\n" 
								                +"#pragma config IESO = OFF       // Internal External Switchover bit (Internal/External Switchover mode is disabled)\n"
								                +"#pragma config FCMEN = OFF      // Fail-Safe Clock Monitor Enabled bit (Fail-Safe Clock Monitor is disabled)\n" 
								                +"#pragma config LVP = OFF        // Low Voltage Programming Enable bit (RB3 pin has digital I/O, HV on MCLR must be used for programming)\n" 
								                +"\n" +"\n" +"\n" 
								                +"// CONFIG2\n"
								                +"\n"
								                +"#pragma config BOR4V = BOR40V   // Brown-out Reset Selection bit (Brown-out Reset set to 4.0V)\n"
								                +"\n"
								                +"#pragma config WRT = OFF        // Flash Program Memory Self Write Enable bits (Write protection off)\n\n\n\n"));
          }
        case 214: break;
        case 136: 
          { return symbol(sym.RETARDO,new String("\n\n\tvoid retardo(unsigned int i){for(;i>0;i--);}\n\n"));
          }
        case 215: break;
        case 98: 
          { return symbol(sym.PC4,new String("\tPORTCbits.RC4"));
          }
        case 216: break;
        case 76: 
          { return symbol(sym.TE,new String("\tTRISEbits.TRISE3"));
          }
        case 217: break;
        case 62: 
          { return symbol(sym.TC,new String("\tTRISCbits.TRISC5"));
          }
        case 218: break;
        case 118: 
          { return symbol(sym.THEN);
          }
        case 219: break;
        case 112: 
          { return symbol(sym.PE2,new String("\tPORTEbits.RE2"));
          }
        case 220: break;
        case 28: 
          { return symbol(sym.PA,new String("\tPORTA"));
          }
        case 221: break;
        case 51: 
          { return symbol(sym.TA,new String("\tTRISBbits.TRISB2"));
          }
        case 222: break;
        case 38: 
          { return symbol(sym.MENORIGUAL);
          }
        case 223: break;
        case 30: 
          { return symbol(sym.PC,new String("\tPORTC"));
          }
        case 224: break;
        case 105: 
          { return symbol(sym.PD3,new String("\tPORTDbits.RD3"));
          }
        case 225: break;
        case 89: 
          { return symbol(sym.PB3,new String("\tPORTBbits.RB3"));
          }
        case 226: break;
        case 69: 
          { return symbol(sym.TD,new String("\tTRISDbits.TRISD4"));
          }
        case 227: break;
        case 135: 
          { return symbol(sym.ENTRADA);
          }
        case 228: break;
        case 19: 
          { ;
          }
        case 229: break;
        case 39: 
          { return symbol(sym.IGUAL2);
          }
        case 230: break;
        case 32: 
          { return symbol(sym.PE,new String("\tPORTE"));
          }
        case 231: break;
        case 43: 
          { return symbol(sym.TA,new String("\tTRISAbits.TRISA2"));
          }
        case 232: break;
        case 5: 
          { return symbol(sym.LCORCH);
          }
        case 233: break;
        case 16: 
          { return symbol(sym.MAYOR);
          }
        case 234: break;
        case 20: 
          { return symbol(sym.ID, yytext());
          }
        case 235: break;
        case 82: 
          { return symbol(sym.PA4,new String("\tPORTAbits.RA4"));
          }
        case 236: break;
        case 56: 
          { return symbol(sym.TA,new String("\tTRISBbits.TRISB7"));
          }
        case 237: break;
        case 117: 
          { return symbol(sym.CTELOGICA);
          }
        case 238: break;
        case 121: 
          { return symbol(sym.CHAR);
          }
        case 239: break;
        case 115: 
          { return symbol(sym.TIPOVC);
          }
        case 240: break;
        case 124: 
          { return symbol(sym.SETUP,new String("\tvoid setup()"));
          }
        case 241: break;
        case 119: 
          { return symbol(sym.MAIN,new String("\n\n\tvoid main(void)"));
          }
        case 242: break;
        case 48: 
          { return symbol(sym.TA,new String("\tTRISAbits.TRISA7"));
          }
        case 243: break;
        case 96: 
          { return symbol(sym.PC2,new String("\tPORTCbits.RC2"));
          }
        case 244: break;
        case 13: 
          { return symbol(sym.PCOMA);
          }
        case 245: break;
        case 116: 
          { return symbol(sym.CARACTER);
          }
        case 246: break;
        case 110: 
          { return symbol(sym.PE0,new String("\tPORTEbits.RE0"));
          }
        case 247: break;
        case 75: 
          { return symbol(sym.TE,new String("\tTRISEbits.TRISE2"));
          }
        case 248: break;
        case 61: 
          { return symbol(sym.TC,new String("\tTRISCbits.TRISC4"));
          }
        case 249: break;
        case 21: 
          { return symbol(sym.TA,new String("\tTRISA"));
          }
        case 250: break;
        case 2: 
          { return symbol(sym.NMETODO, new String(yytext()));
          }
        case 251: break;
        case 103: 
          { return symbol(sym.PD1,new String("\tPORTDbits.RD1"));
          }
        case 252: break;
        case 87: 
          { return symbol(sym.PB1,new String("\tPORTBbits.RB1"));
          }
        case 253: break;
        case 122: 
          { return symbol(sym.REAL);
          }
        case 254: break;
        case 50: 
          { return symbol(sym.TA,new String("\tTRISBbits.TRISB1"));
          }
        case 255: break;
        case 101: 
          { return symbol(sym.PC7,new String("\tPORTCbits.RC7"));
          }
        case 256: break;
        case 23: 
          { return symbol(sym.TC,new String("\tTRISC"));
          }
        case 257: break;
        case 18: 
          { return symbol(sym.IGUAL);
          }
        case 258: break;
        case 138: 
          { return symbol(sym.OTHERWISE);
          }
        case 259: break;
        case 68: 
          { return symbol(sym.TD,new String("\tTRISDbits.TRISD3"));
          }
        case 260: break;
        case 77: 
          { return symbol(sym.FIN);
          }
        case 261: break;
        case 80: 
          { return symbol(sym.PA2,new String("\tPORTAbits.RA2"));
          }
        case 262: break;
        case 25: 
          { return symbol(sym.TE,new String("\tTRISE"));
          }
        case 263: break;
        case 9: 
          { return symbol(sym.RPAREN);
          }
        case 264: break;
        case 42: 
          { return symbol(sym.TA,new String("\tTRISAbits.TRISA1"));
          }
        case 265: break;
        case 131: 
          { return symbol(sym.SALIDA);
          }
        case 266: break;
        case 55: 
          { return symbol(sym.TA,new String("\tTRISBbits.TRISB6"));
          }
        case 267: break;
        case 94: 
          { return symbol(sym.PC0,new String("\tPORTCbits.RC0"));
          }
        case 268: break;
        case 108: 
          { return symbol(sym.PD6,new String("\tPORTDbits.RD6"));
          }
        case 269: break;
        case 92: 
          { return symbol(sym.PB6,new String("\tPORTBbits.RB6"));
          }
        case 270: break;
        case 47: 
          { return symbol(sym.TA,new String("\tTRISAbits.TRISA6"));
          }
        case 271: break;
        case 37: 
          { return symbol(sym.MAYORIGUAL);
          }
        case 272: break;
        case 137: 
          { return symbol(sym.INTEGER);
          }
        case 273: break;
        case 85: 
          { return symbol(sym.PA7,new String("\tPORTAbits.RA7"));
          }
        case 274: break;
        case 129: 
          { return symbol(sym.CHALE,new String("\t\tretardo"));
          }
        case 275: break;
        case 74: 
          { return symbol(sym.TE,new String("\tTRISEbits.TRISE1"));
          }
        case 276: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
